language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
addons:
  postgresql: "9.3"
before_script:
  - "npm install"
  - "npm install -g sequelize-cli"
  - "psql -c 'create database sms-express-test;' -U postgres"
  - "cp config/database.yml.travis config/database.yml"
script:
  - "npm test"
services:
  - postgresql
